# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            t0nc4
tagline:          'Geek in General'
description:      'Te Nol En Ce Empat'
url:              http://t0nc4.github.io
baseurl:          /

author:
  name:           'Tonca Han'
  url:            https://twitter.com/t0nc4

paginate:         1

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde


